# Generated by Django 5.0.2 on 2024-03-28 21:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0003_historicdata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicdata",
            name="all_time_profit",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
