# Generated by Django 5.0.2 on 2024-03-28 23:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0005_historicdata_all_time_profit_percentage"),
    ]

    operations = [
        migrations.AddField(
            model_name="holding",
            name="all_time_profit",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
        migrations.AlterField(
            model_name="holding",
            name="avg_price",
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
        migrations.AlterField(
            model_name="holding",
            name="quantity",
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
        migrations.DeleteModel(
            name="HistoricData",
        ),
    ]
