# Generated by Django 5.0.2 on 2024-03-29 02:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0006_holding_all_time_profit_alter_holding_avg_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="holding",
            name="total_buy",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
    ]
