# Generated by Django 5.0.2 on 2024-03-29 23:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0007_holding_total_buy"),
    ]

    operations = [
        migrations.AddField(
            model_name="holding",
            name="total_buy_spent",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
    ]
