# Generated by Django 5.0.2 on 2024-04-10 16:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0009_transaction_profit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="profit",
        ),
    ]
