# Generated by Django 5.0.2 on 2024-04-22 02:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0011_holding_total_sell_value"),
    ]

    operations = [
        migrations.CreateModel(
            name="SP500Data",
            fields=[
                ("date", models.DateField(primary_key=True, serialize=False)),
                ("percent_change", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
