# Generated by Django 5.0.2 on 2024-04-22 03:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0012_sp500data"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sp500data",
            old_name="percent_change",
            new_name="price",
        ),
    ]
