# Generated by Django 5.0 on 2023-12-13 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paypal', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paypalproduct',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='paypalproduct',
            name='name',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='paypalproduct',
            name='unique_name',
        ),
    ]
