# Generated by Django 5.0 on 2023-12-13 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paypal', '0002_alter_paypalproduct_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paypalproduct',
            name='paypal_id_product',
            field=models.CharField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
