# Generated by Django 5.0 on 2023-12-13 22:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paypal', '0003_paypalproduct_paypal_id_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaypalProduct',
            new_name='PaypalProductModel',
        ),
    ]
