# Generated by Django 5.0.2 on 2024-03-05 01:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paypal", "0005_purchase"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paypalproductmodel",
            name="price",
        ),
        migrations.AlterField(
            model_name="paypalproductmodel",
            name="paypal_id_product",
            field=models.CharField(
                help_text="The product ID will be generated once saved.",
                max_length=200,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="paypalproductmodel",
            name="user",
            field=models.ForeignKey(
                limit_choices_to={"is_superuser": True},
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
